#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: "2"

services:
    tfg-db:
      image: postgres:11.1
      volumes:
        - postgres:/pgdata
        - ./config/init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      env_file:
        - ./config/environment/development.env
      ports:
        - "5432:5432"

    tfg-webserver:
      image: nginx:1.15
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - tfg-webapp
      volumes:
        - ./config/webserver/nginx.tmpl:/etc/nginx/conf.d/nginx.tmpl
        - ./config/webserver/localhost.crt:/etc/ssl/certs/localhost.crt
        - ./config/webserver/localhost.key:/etc/ssl/private/localhost.key
        - ./static-files:/srv/static-files
      env_file:
        - ./config/environment/development.env
      command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.tmpl > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

    tfg-webapp:
      build:
        context: webapp
      volumes:
        - ./webapp/tfgproject:/srv/tfgproject
        - ./static-files:/srv/static-files
      expose:
        - "8000"
      links:
        - tfg-db
      depends_on:
        - tfg-db
      env_file:
        - ./config/environment/development.env

volumes:
  static-files:
    driver: local
  postgres: 
    driver: local
